---
title: "desity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(destiny)
library(Biobase)
library(DESeq2)
```


```{r}
obj <- readRDS("/mnt/raid62/Lung_cancer_10x/00_data_ingest/04_rds_generated/seurat_obj/Neuroendocrine_processed.rds")
```

# 按照每个不同Stage获取到不同时期中所有细胞的总表达量
```{r}
stage = unique(obj@meta.data$Stage)

exp = NULL
for(i in stage) {
    temp <- rowSums(obj@raw.data[, rownames(obj@meta.data[obj@meta.data$Stage == i,])])
    temp <- as.data.frame(temp)
    colnames(temp) <- i
    
    if(is.null(exp)) {
        exp = temp
    } else {
        exp = merge(exp, temp, by = 0)
        rownames(exp) <- exp$Row.names
        exp <- exp[, !colnames(exp) %in% c("Row.names")]
    }
}

```

# 借助DESeq2完成normalization
```{r}
coldata <- data.frame(stage = stage)

dds <- DESeqDataSetFromMatrix(countData = exp,
                              colData = coldata,
                              design = ~ stage)

dds <- estimateSizeFactors(dds)

normalized <- counts(dds, normalized=TRUE)
```

# 创建desity

```{r}
rownames(coldata) <- coldata$stage
pd <- new('AnnotatedDataFrame', data = as.data.frame(coldata))
obj_set <- ExpressionSet(
    assayData=normalized,
    phenoData=pd
)
```

```{r}
dm <- DiffusionMap(obj_set)

plot(dm,col_by='Stage')

dpt <- DPT(dm)

plot(dpt)

plot(dpt, col_by = 'Stage')
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
