---
title: "Mfuzz_radar_and_pca"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(openxlsx)
library(ggradar)
library(dplyr)
library(scales)
library(tibble)
library(reshape2)
library(stringr)
library(doMC)
library(cowplot)
library(reticulate)
library(ggfortify)
library(SingleCellExperiment)
```


## Read data

```{r}
sysu_luad <- read.csv("/mnt/raid62/Lung_cancer_10x/SYSU/ADC.csv", row.names = 1)
sysu_lusc <- read.csv("/mnt/raid62/Lung_cancer_10x/SYSU/SCC.csv", row.names = 1)
```


## Read TCGA data
```{r}
tcga_luad = readRDS("/mnt/raid62/Lung_cancer_10x/TCGA/LUAD.rds")
tcga_lusc = readRDS("/mnt/raid62/Lung_cancer_10x/TCGA/LUAD.rds")
```


## LUSC Basal with PS06

```{r}
obj <- readRDS("/mnt/raid62/Lung_cancer_10x/final_plots/03_each_cells/LUSC/Basal_wo_PS06/seurat.rds")

module <- read.csv("/mnt/raid62/Lung_cancer_10x/final_plots/03_each_cells/LUSC/Basal_wo_PS06/mfuzz/results.csv", row.names = 1)
```

```{r}
mtcars_radar <- mtcars %>% 
  as_tibble(rownames = "group") %>% 
  mutate_at(vars(-group), rescale) %>% 
  tail(4) %>% 
  select(1:10)
```

```{r}
ggradar(mtcars_radar)
```

```{r fig.height=6, fig.width=6}
format_radar_expr_mat <- function(
  obj, 
  module,
  legend.position="bottom",
  plot.title="",
  legend.title = "",
  axis.label.size = 5
) {
    cells = obj@meta.data[, "Stage", drop = F]
    cells$Cells = rownames(cells)
    
    mat = obj@scale.data[as.character(module$gene), ]
    
    mat = melt(as.matrix(mat))
    mat = merge(cells, mat, by.x = "Cells", by.y = "Var2")
    
    module$Clt = as.character(module$Clt)
    module$Clt = sapply(module$Clt, function(x) { paste0("M.", x) })
    
    module = merge(module, mat, by.x = "gene", by.y = "Var1", all.x = T)
    
    module = module %>% group_by(Clt, Stage, gene) %>%
        mutate(m = mean(value)) %>%
        dplyr::select(Clt, Stage, m) %>%
        unique() %>%
        group_by(Clt, Stage) %>%
        mutate(value = mean(m)) %>%
        dplyr::select(Clt, Stage, value) %>%
        unique()

    p <- ggradar(
      dcast(module, Stage~Clt), 
      centre.y = floor(min(module$value)), 
      values.radar = round(seq(from=floor(min(module$value)), to=max(module$value), length.out = 3), 2),
      grid.max = ceiling(max(module$value)),
      legend.position = legend.position,
      legend.title = legend.title,
      plot.title = plot.title,
      axis.label.size = axis.label.size,
      group.line.width = 0.5,
      group.point.size = 4,
      group.colours = c(
          "I"="#EC7A21", 
          "II"="#D73F47", 
          "III"="#65A9A3", 
          "IV"="#4A933E", 
          "LUAD_Normal"="#FECC1B", 
          "LUSC_Normal"="#DA6906"
        )
    )
    return(p)
}
```

## Test module on SYSU data
```{r}
format_radar_sysu_expr_mat <- function(
  expr, 
  module,
  legend.position="bottom",
  plot.title="",
  legend.title = "",
  axis.label.size = 5
) {
    cells = data.frame(
      Stage = sapply(colnames(expr), function(x) {
        str_split(x, "_")[[1]][4]
      }),
      Cells = colnames(expr),
      stringsAsFactors = F
    )

    mat = expr[intersect(rownames(expr), as.character(module$gene)), ]
    mat = scale(mat)
    mat = melt(as.matrix(mat))
    mat = merge(cells, mat, by.x = "Cells", by.y = "Var2")
    
    module$Clt = as.character(module$Clt)
    module$Clt = sapply(module$Clt, function(x) { paste0("M.", x) })
    
    module = merge(module, mat, by.x = "gene", by.y = "Var1")

    module = module %>% group_by(Clt, Stage, gene) %>%
        mutate(m = mean(value)) %>%
        dplyr::select(Clt, Stage, m) %>%
        unique() %>%
        group_by(Clt, Stage) %>%
        mutate(value = mean(m)) %>%
        dplyr::select(Clt, Stage, value) %>%
        unique()
    
    # module$value = log2(module$value + 1)
    
    plot.data = dcast(module, Stage~Clt)
    plot.data = na.omit(plot.data)
    # plot.data[is.na(plot.data), 2:ncol(plot.data)] = floor(min(plot.data[!is.na(plot.data[2:ncol(plot.data)]), 2:ncol(plot.data)]))
   
    p <- ggradar(
        plot.data,
        centre.y = floor(min(module$value)),
        values.radar = round(seq(from=floor(min(module$value)), to=max(module$value), length.out = 3), 2),
        grid.max = ceiling(max(module$value)),
        legend.position = legend.position,
        legend.title = legend.title,
        plot.title = plot.title,
        axis.label.size = axis.label.size,
        group.line.width = 0.5,
        group.point.size = 4,
        group.colours = c(
            "I"="#EC7A21",
            "II"="#D73F47",
            "III"="#65A9A3",
            "IV"="#4A933E",
            "LUAD_Normal"="#FECC1B",
            "LUSC_Normal"="#DA6906"
          )
      )
    return(p)
}
```


## Test module on TCGA data
```{r}
format_radar_tcga_expr_mat <- function(
  expr, 
  module,
  legend.position="bottom",
  plot.title="",
  legend.title = "",
  axis.label.size = 5
) {
    meta = colData(expr)@listData
  
    cells = data.frame(
      Stage = sapply(meta$tumor_stage, function(x) {
        if(x != "not reported") {
          x = str_to_upper(str_replace_all(x, "[^iv]", ""))
        }
        return(x)
      }),
      Cells = meta$barcode,
      stringsAsFactors = F
    )

    mat = assay(expr, "raw_count")
    rownames(mat) = sapply(rownames(mat), function(x) { str_split(x, "\\|")[[1]][1] })

    mat = scale(mat)
    mat = melt(as.matrix(mat))
    mat = merge(cells, mat, by.x = "Cells", by.y = "Var2")

    module$Clt = as.character(module$Clt)
    module$Clt = sapply(module$Clt, function(x) { paste0("M.", x) })

    module = merge(module, mat, by.x = "gene", by.y = "Var1")

    module = module %>% group_by(Clt, Stage, gene) %>%
        mutate(m = mean(value)) %>%
        dplyr::select(Clt, Stage, m) %>%
        unique() %>%
        group_by(Clt, Stage) %>%
        mutate(value = mean(m)) %>%
        dplyr::select(Clt, Stage, value) %>%
        unique()

    # module$value = log2(module$value + 1)
    
    plot.data = dcast(module, Stage~Clt)
    plot.data = na.omit(plot.data)
    # plot.data[is.na(plot.data), 2:ncol(plot.data)] = floor(min(plot.data[!is.na(plot.data[2:ncol(plot.data)]), 2:ncol(plot.data)]))

    p <- ggradar(
        plot.data,
        centre.y = floor(min(module$value)),
        values.radar = round(seq(from=floor(min(module$value)), to=max(module$value), length.out = 3), 2),
        grid.max = ceiling(max(module$value)),
        legend.position = legend.position,
        legend.title = legend.title,
        plot.title = plot.title,
        axis.label.size = axis.label.size,
        group.line.width = 0.5,
        group.point.size = 4,
        group.colours = c(
            "I"="#EC7A21",
            "II"="#D73F47",
            "III"="#65A9A3",
            "IV"="#4A933E",
            "LUAD_Normal"="#FECC1B",
            "LUSC_Normal"="#DA6906",
            "not reported"="grey"
          )
      )
    return(p)
}
```



## make radar plots
```{r}
glob = import("glob")

files = glob$glob("/mnt/raid62/Lung_cancer_10x/final_plots/03_each_cells/LUSC/*/mfuzz/results.csv")

registerDoMC(20)
foreach(i=files) %dopar% {
    module = read.csv(i, row.names = 1)
    obj <- readRDS(paste(dirname(dirname(i)), "seurat.rds", sep = "/"))
    
    p1 <- format_radar_expr_mat(
        obj, 
        module,
        legend.position="bottom",
        plot.title=basename(dirname(dirname(i))),
        legend.title = "",
        axis.label.size = 5
    )
    
    p2 <- format_radar_sysu_expr_mat(
        sysu_lusc,
        module,
        legend.position="bottom",
        plot.title=paste0(basename(dirname(dirname(i))), "(SYSU)"),
        legend.title = "",
        axis.label.size = 5
    )
    
    p3 <- format_radar_tcga_expr_mat(
        tcga_lusc,
        module,
        legend.position="bottom",
        plot.title=paste0(basename(dirname(dirname(i))), "(TCGA)"),
        legend.title = "",
        axis.label.size = 5
    )
      
    output_dir = dirname(i)
    
    ggsave(
        filename = paste(output_dir, "mfuzz_radar.pdf", sep = "/"),
        plot = p1,
        width = 6,
        height = 6,
        dpi = 600,
        units = "in"
    )
    
    ggsave(
        filename = paste(output_dir, "mfuzz_radar_bulk.pdf", sep = "/"),
        plot = plot_grid(p2, p3, nrow = 1),
        width = 12,
        height = 6,
        dpi = 600,
        units = "in"
    )
    
} 
```

```{r}
files = glob$glob("/mnt/raid62/Lung_cancer_10x/final_plots/03_each_cells/LUAD/*/mfuzz/results.csv")

registerDoMC(20)
foreach(i=files) %dopar% {
    module = read.csv(i, row.names = 1)
    obj <- readRDS(paste(dirname(dirname(i)), "seurat.rds", sep = "/"))
    
    p1 <- format_radar_expr_mat(
        obj, 
        module,
        legend.position="bottom",
        plot.title=basename(dirname(dirname(i))),
        legend.title = "",
        axis.label.size = 5
    )
    
    p2 <- format_radar_sysu_expr_mat(
        sysu_luad,
        module,
        legend.position="bottom",
        plot.title=paste0(basename(dirname(dirname(i))), "(SYSU)"),
        legend.title = "",
        axis.label.size = 5
    )
    
    p3 <- format_radar_tcga_expr_mat(
        tcga_luad,
        module,
        legend.position="bottom",
        plot.title=paste0(basename(dirname(dirname(i))), "(TCGA)"),
        legend.title = "",
        axis.label.size = 5
    )
      
    output_dir = dirname(i)
    
    ggsave(
        filename = paste(output_dir, "mfuzz_radar.pdf", sep = "/"),
        plot = p1,
        width = 6,
        height = 6,
        dpi = 600,
        units = "in"
    )
    
    ggsave(
        filename = paste(output_dir, "mfuzz_radar_bulk.pdf", sep = "/"),
        plot = plot_grid(p2, p3, nrow = 1),
        width = 12,
        height = 6,
        dpi = 600,
        units = "in"
    )
    
} 
```


---


## make PCA plots
### make single cell
```{r fig.height=12, fig.width=18}
format_pca_expr_mat <- function(
    obj,
    module,
    n.pcs=6,
    legend.title = ""
) {
    mat = obj@scale.data[unique(as.character(module$gene)), ]
    pca = prcomp(t(mat), scale. = F, center = F)
    
    plist = list()
    
    for(i in 1:(n.pcs - 1)) {
        p <- autoplot(pca, x=i, y=i+1, data = obj@meta.data, colour = 'Stage') + 
          scale_color_manual(
              values = c(
                  "I"="#EC7A21",
                  "II"="#D73F47",
                  "III"="#65A9A3",
                  "IV"="#4A933E",
                  "LUAD_Normal"="#FECC1B",
                  "LUSC_Normal"="#DA6906",
                  "not reported"="grey"
                )
          ) +
          theme_bw() +
          theme(
            legend.position = "none",
            axis.text = element_text(size = 20),
            axis.title = element_text(size = 20),
            legend.text = element_text(size = 20)
          )
        
          plist[[length(plist) + 1]] = p
    }
    
    sample = autoplot(pca, x=1, y=2, data = obj@meta.data, colour = 'Stage') +
      scale_color_manual(
          values = c(
              "I"="#EC7A21",
              "II"="#D73F47",
              "III"="#65A9A3",
              "IV"="#4A933E",
              "LUAD_Normal"="#FECC1B",
              "LUSC_Normal"="#DA6906",
              "not reported"="grey"
          )
      ) +
      guides(color = guide_legend(override.aes = list(size = 10))) +
      theme(
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
      ) +
      labs(color=legend.title)

    plist[[length(plist) + 1]] = get_legend(sample)
    return(plist)
}

# plist = format_pca_expr_mat(obj, module)

# plot_grid(plotlist = plist, ncol = 3)
```


### make sysu
```{r fig.height=12, fig.width=18}
format_pca_sysu_expr_mat <- function(
    expr,
    module,
    n.pcs=6,
    legend.title = ""
) {
  
    cells = data.frame(
        Stage = sapply(colnames(expr), function(x) {
          str_split(x, "_")[[1]][4]
        }),
        Cells = colnames(expr),
        stringsAsFactors = F
    )

    mat = expr[intersect(rownames(expr), as.character(module$gene)), ]
    pca = prcomp(t(mat), scale. = F, center = F)
    
    plist = list()
    
    for(i in 1:(n.pcs - 1)) {
        p <- autoplot(pca, x=i, y=i+1, data = cells, colour = 'Stage') + 
          scale_color_manual(
              values = c(
                  "I"="#EC7A21",
                  "II"="#D73F47",
                  "III"="#65A9A3",
                  "IV"="#4A933E",
                  "LUAD_Normal"="#FECC1B",
                  "LUSC_Normal"="#DA6906",
                  "not reported"="grey"
                )
          ) +
          theme_bw() +
          theme(
            legend.position = "none",
            axis.text = element_text(size = 20),
            axis.title = element_text(size = 20),
            legend.text = element_text(size = 20)
          )
        
          plist[[length(plist) + 1]] = p
    }
    
    sample = autoplot(pca, x=1, y=2, data = cells, colour = 'Stage') +
      scale_color_manual(
          values = c(
              "I"="#EC7A21",
              "II"="#D73F47",
              "III"="#65A9A3",
              "IV"="#4A933E",
              "LUAD_Normal"="#FECC1B",
              "LUSC_Normal"="#DA6906",
              "not reported"="grey"
          )
      ) +
      guides(color = guide_legend(override.aes = list(size = 10))) +
      theme(
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
      ) +
      labs(color=legend.title)

    plist[[length(plist) + 1]] = get_legend(sample)
    return(plist)
}

# plist = format_pca_sysu_expr_mat(sysu_lusc, module)
# 
# plot_grid(plotlist = plist, ncol = 3)
```



## Test module on TCGA data
```{r}
format_pca_tcga_expr_mat <- function(
  expr, 
  module,
  n.pcs=6,
  legend.title = ""
) {
    meta = colData(expr)@listData
  
    cells = data.frame(
      Stage = sapply(meta$tumor_stage, function(x) {
        if(x != "not reported") {
          x = str_to_upper(str_replace_all(x, "[^iv]", ""))
        }
        return(x)
      }),
      Cells = meta$barcode,
      stringsAsFactors = F
    )

    mat = assay(expr, "raw_count")
    rownames(mat) = sapply(rownames(mat), function(x) { str_split(x, "\\|")[[1]][1] })

    mat = mat[intersect(rownames(mat), as.character(module$gene)), ]
    print(typeof(mat))
    
    pca = prcomp(t(mat), scale. = F, center = F)
    
    plist = list()
    
    for(i in 1:(n.pcs - 1)) {
        p <- autoplot(pca, x=i, y=i+1, data = cells, colour = 'Stage') + 
          scale_color_manual(
              values = c(
                  "I"="#EC7A21",
                  "II"="#D73F47",
                  "III"="#65A9A3",
                  "IV"="#4A933E",
                  "LUAD_Normal"="#FECC1B",
                  "LUSC_Normal"="#DA6906",
                  "not reported"="grey"
                )
          ) +
          theme_bw() +
          theme(
            legend.position = "none",
            axis.text = element_text(size = 20),
            axis.title = element_text(size = 20),
            legend.text = element_text(size = 20)
          )
        
          plist[[length(plist) + 1]] = p
    }
    
    sample = autoplot(pca, x=1, y=2, data = cells, colour = 'Stage') +
      scale_color_manual(
          values = c(
              "I"="#EC7A21",
              "II"="#D73F47",
              "III"="#65A9A3",
              "IV"="#4A933E",
              "LUAD_Normal"="#FECC1B",
              "LUSC_Normal"="#DA6906",
              "not reported"="grey"
          )
      ) +
      guides(color = guide_legend(override.aes = list(size = 10))) +
      theme(
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)
      ) +
      labs(color=legend.title)

    plist[[length(plist) + 1]] = get_legend(sample)
    return(plist)
}
# plist = format_pca_tcga_expr_mat(tcga_lusc, module)
# 
# plot_grid(plotlist = plist, ncol = 3)
```


## make pca plots
```{r}
files = glob$glob("/mnt/raid62/Lung_cancer_10x/final_plots/03_each_cells/LUSC/*/mfuzz/results.csv")

registerDoMC(20)
foreach(i=files) %dopar% {
    module = read.csv(i, row.names = 1)
    obj <- readRDS(paste(dirname(dirname(i)), "seurat.rds", sep = "/"))
    
    p1 <- format_pca_expr_mat(
        obj, 
        module,
        n.pcs = 6,
        legend.title = basename(dirname(dirname(i)))
    )
    p1 <- plot_grid(plotlist = p1, ncol = 3)
    
    p2 <- format_pca_sysu_expr_mat(
        sysu_lusc,
        module,
        n.pcs = 6,
        legend.title = paste0(basename(dirname(dirname(i))), "(SYSU)")
    )
    p2 <- plot_grid(plotlist = p2, ncol = 3)
    
    p3 <- format_pca_tcga_expr_mat(
        tcga_lusc,
        module,
        n.pcs = 6,
        legend.title = paste0(basename(dirname(dirname(i))), "(TCGA)")
    )
    p3 <- plot_grid(plotlist = p3, ncol = 3)
      
    output_dir = dirname(i)
    
    ggsave(
        filename = paste(output_dir, "mfuzz_pca.pdf", sep = "/"),
        plot = p1,
        width = 6,
        height = 6,
        dpi = 600,
        units = "in"
    )
    
    ggsave(
        filename = paste(output_dir, "mfuzz_pca_bulk.pdf", sep = "/"),
        plot = plot_grid(p2, p3, nrow = 1),
        width = 12,
        height = 6,
        dpi = 600,
        units = "in"
    )
    
} 
```



```{r}
files = glob$glob("/mnt/raid62/Lung_cancer_10x/final_plots/03_each_cells/LUAD/*/mfuzz/results.csv")

registerDoMC(20)
foreach(i=files) %dopar% {
    module = read.csv(i, row.names = 1)
    obj <- readRDS(paste(dirname(dirname(i)), "seurat.rds", sep = "/"))
    
    p1 <- format_pca_expr_mat(
        obj, 
        module,
        n.pcs = 6,
        legend.title = basename(dirname(dirname(i)))
    )
    p1 <- plot_grid(plotlist = p1, ncol = 3)
    
    p2 <- format_pca_sysu_expr_mat(
        sysu_luad,
        module,
        n.pcs = 6,
        legend.title = paste0(basename(dirname(dirname(i))), "(SYSU)")
    )
    p2 <- plot_grid(plotlist = p2, ncol = 3)
    
    p3 <- format_pca_tcga_expr_mat(
        tcga_luad,
        module,
        n.pcs = 6,
        legend.title = paste0(basename(dirname(dirname(i))), "(TCGA)")
    )
    p3 <- plot_grid(plotlist = p3, ncol = 3)
      
    output_dir = dirname(i)
    
    ggsave(
        filename = paste(output_dir, "mfuzz_pca.pdf", sep = "/"),
        plot = p1,
        width = 6,
        height = 6,
        dpi = 600,
        units = "in"
    )
    
    ggsave(
        filename = paste(output_dir, "mfuzz_pca_bulk.pdf", sep = "/"),
        plot = plot_grid(p2, p3, nrow = 1),
        width = 12,
        height = 6,
        dpi = 600,
        units = "in"
    )
    
} 
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
