---
title: "Volcano_plots"
author: "Zhang Yiming"
date: "7/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(openxlsx)
library(ggplot2)
library(ggrepel)
```


```{R}
anova <- read.xlsx("/mnt/raid62/Lung_cancer_10x/07_gene_drug/All_DEGS.xlsx", sheet = 1)
limma <- read.xlsx("/mnt/raid62/Lung_cancer_10x/07_gene_drug/All_DEGS.xlsx", sheet = 2)
top10 <- read.xlsx("/mnt/raid62/Lung_cancer_10x/07_gene_drug/All_DEGS.xlsx", sheet = 3)

gene_drugs <- read.xlsx("/mnt/raid62/Lung_cancer_10x/07_gene_drug/gene_drug.xlsx")
```

## Including Plots


```{r pressure, echo=FALSE}

make_voca_plot <- function(data, genes.label, genes.use = NULL, logFC="logFC", pval="adjp", log = TRUE) {

    if (is.null(genes.use)) {
        genes.use = unique(data$Symbol)
    } 

    data = data[data$Symbol %in% genes.use, ]

    data$ident[
        as.numeric(data[, logFC]) > 1 & as.numeric(data[, pval]) < 0.05
    ] = "1"

    data$ident[
        as.numeric(data[, logFC]) < -1 & as.numeric(data[, pval]) < 0.05
    ] = "2"

    data$ident[
        abs(as.numeric(data[, logFC])) <= 1 | as.numeric(data[, pval]) >= 0.05
    ] = "3" 

    # data$ident <- apply(data, 1, function(row) {
    #     if (row[2] > 0.25 && row[5] < 0.05) {
    #         return("1")
    #     } else if (row[2] < -0.25 && row[5] < 0.05) {
    #         return("2")
    #     } 
        
    #     return("3")
    # })
    
    if (log) {
        data[, pval] <- -log10(as.numeric(data[, pval]))
    } else {
        data[, pval] <- as.numeric(data[, pval])
    }
    
    # data$gene <- rownames(data)
    data$Symbol = as.factor(data$Symbol)
    
    data[, logFC] <- as.numeric(data[, logFC])

    p <- eval(
        parse(
            text = paste(
                "ggplot(data = data, aes(x=", logFC, ", y=", pval, ", color = ident))"
            )
        )
    )
    
    p <- p + 
        geom_point() + 
        scale_color_manual(values=c(
            "1"="red", 
            "2"="green", 
            "3"="grey50"
        )) +
        geom_text_repel(
            aes(label=ifelse(Symbol %in% genes.label, as.character(Symbol),''))
        ) + theme_bw() +
        theme(legend.position = "none")
    
    if(log) {
        p = p + labs(x="log2(FC)", y="-log10(FDR)")
    } else {
        p = p + labs(x="log2(FC)", y="Percentage")
    }
        

    return(p)
}
```


### ANOVA LUAD
```{r fig.height=6, fig.width=6}
make_voca_plot(anova[anova$disease == "LUAD", ], genes.label=gene_drugs$Symbol[gene_drugs$matters > 0], genes.use = NULL, logFC="logFC", pval="adjp", log = TRUE)
```

### ANOVA LUSC
```{r fig.height=6, fig.width=6}
make_voca_plot(anova[anova$disease == "LUSC", ], genes.label=gene_drugs$Symbol[gene_drugs$matters > 0], genes.use = NULL, logFC="logFC", pval="adjp", log = TRUE)
```

### LIMMA LUSC
```{r fig.height=6, fig.width=6}
make_voca_plot(limma[limma$disease == "LUSC", ], genes.label=gene_drugs$Symbol[gene_drugs$matters > 0], genes.use = NULL, logFC="logFC", pval="adjp", log = TRUE)
```


### TOP10 LUAD
```{r fig.height=6, fig.width=6}
make_voca_plot(top10[top10$disease == "LUAD", ], genes.label=gene_drugs$Symbol[gene_drugs$matters > 0], genes.use = NULL, logFC="logFC", pval="Percentage", log = FALSE)
```


### TOP10 LUSC
```{r fig.height=6, fig.width=6}
make_voca_plot(top10[top10$disease == "LUSC", ], genes.label=gene_drugs$Symbol[gene_drugs$matters > 0], genes.use = NULL, logFC="logFC", pval="Percentage", log = FALSE)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
