---
title: "Basal"
author: "Zhang Yiming"
date: "2019/7/1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(openxlsx)
library(reshape2)
library(dplyr)
library(ComplexHeatmap)
library(circlize)
```

```{r}
full.path = function(path) {
    return(paste("/mnt/raid62/Lung_cancer_10x/MetaCell", path, sep = "/"))
}


# R is mess up
read_lfp <- function(path) {
    data = read.csv(path, header = T, row.names = 1)
    
    mat = matrix(NA, nrow = nrow(data), ncol = ncol(data))
    
    for(i in 1:length(data)) {
        mat[, i] = data[[i]]
    }
    
    rownames(mat) <- rownames(data)
    colnames(mat) <- names(data)
    as.matrix(mat)
}
```

```{r}
obj <- readRDS("/mnt/raid62/Lung_cancer_10x/02_figures_each_cell/Basal_SCC/Basal.rds")
```

This is how to export lfp value
```{R}
load("/mnt/raid62/Lung_cancer_10x/MetaCell/By_cells/Basal_SCC/mat.Basal_SCC.Rda")
scmat = object


load("/mnt/raid62/Lung_cancer_10x/MetaCell/By_cells/Basal_SCC/mc.Basal_SCC_mc_f.Rda")
mc = object

load("/mnt/raid62/Lung_cancer_10x/MetaCell/By_cells/Basal_SCC/gstat.Basal_SCC.Rda")
gstat = object

out_df = rbind(tapply(colSums(scmat@mat[, names(mc@mc)]), mc@mc, mean), table(mc@mc))
out_df = cbind(rep("", nrow(out_df)), out_df)


fp_max = apply(mc@mc_fp, 1, max)
fp_tot = gstat[intersect(rownames(mc@mc_fp), rownames(gstat)), "tot"]

# genes to export
f = fp_max > 0 & fp_tot > 0

# actual clust_fp
# out_df = rbind(out_df, cbind(rep("", sum(f)), round(log2(mc@mc_fp[f,]), 2)))
# out_df <- out_df[, 2:ncol(out_df)]

# rownames(out_df)[1:2] = c('mean_umis', 'n_cells')

lfp = round(log2(mc@mc_fp[f,]), 2)
colnames(lfp) <- paste("M", colnames(lfp))
```


```{r}
markers <- read.xlsx("/mnt/raid62/Lung_cancer_10x/02_figures_each_cell/Basal_SCC/annotation_results_by_cluster.xlsx", rowNames = T)

markers <- as.data.frame(markers %>% filter(p_val_adj < 0.05) %>% group_by(ident) %>% top_n(10, wt = avg_logFC))
```

```{R fig.height=15, fig.width=8}
make_heatmap <- function(data, markers) {
    temp = data[markers$gene[markers$gene %in% rownames(data)], ]
    ra = rowAnnotation(cluster = as.factor(markers$ident[markers$gene %in% rownames(data)]))
    
    Heatmap(temp, right_annotation = ra, cluster_rows = F, name = "mat")
}

make_heatmap(lfp, markers)
```

```{r fig.height=12, fig.width=8}
make_heatmap_seurat <- function(obj, data, group.by = "res.0.6") {
    meta = obj@meta.data[order(obj@meta.data[, group.by]), ]

    temp = obj@scale.data[
        markers$gene[markers$gene %in% rownames(data)], 
        rownames(meta)
    ]
    
    ra = rowAnnotation(
        cluster = factor(markers$ident[markers$gene %in% rownames(data)])
    )
    ha = HeatmapAnnotation(
        cluster = factor(meta[, group.by])
    )
    
    Heatmap(temp, right_annotation = ra, top_annotation = ha, cluster_rows = F, cluster_columns=F, name = "mat", show_column_names = F)

}

make_heatmap_seurat(obj, lfp)
# DoHeatmap(obj, genes.use = intersect(markers$gene, rownames(lfp)), group.by = "res.0.6", slim.col.label = T)
```

---
Test Stage module

```{r}
markers <- read.xlsx("/mnt/raid62/Lung_cancer_10x/02_figures_each_cell/Basal_SCC/annotation_results_by_stage.xlsx", rowNames = T)

markers <- as.data.frame(markers %>% filter(p_val_adj < 0.05) %>% group_by(ident) %>% top_n(10, wt = avg_logFC))
```

```{R fig.height=12, fig.width=8}
make_heatmap(lfp, markers)

# pheatmap::pheatmap(lfp[intersect(markers$gene, rownames(lfp)), ], cluster_rows = F)
```

```{r}
make_heatmap_seurat(obj, lfp, group.by = "Stage")
# DoHeatmap(obj, genes.use = intersect(markers$gene, rownames(lfp)), group.by = "Stage", slim.col.label = T)
```

### lets check the percentage of different stage cells

```{r}
clt = as.data.frame(mc@mc)
colnames(clt) = "M"

clt$Stage = obj@meta.data[rownames(clt), "Stage"]
clt$clt = obj@meta.data[rownames(clt), "res.0.6"]
```

```{r}
temp = clt %>% 
    select(M, clt) %>% 
    unique() %>%
    group_by(M, clt) %>% 
    add_tally() %>% 
    group_by(M) %>% 
    mutate(perc = n / sum(n)) %>%
    select(M, clt, perc) %>% 
    unique()

temp = dcast(temp, M~clt, value.var = "perc")

temp$M <- paste0("M", temp$M)

rownames(temp) <- temp$M

temp = temp[, colnames(temp) != "M"]

Heatmap(
    temp, 
    cluster_rows = F, 
    cluster_columns = F, 
    name = "perc",
    cell_fun = function(j, i, x, y, width, height, fill) {
        if(!is.na(temp[i, j ]))
            grid.text(sprintf("%.2f", temp[i, j]), x, y, gp = gpar(fontsize = 10))
    }
)


# pheatmap::pheatmap(temp, number_format = "%.2f", display_numbers = T, cluster_rows = F, cluster_cols = F)
```



```{r}
temp = clt %>% 
    select(M, Stage) %>% 
    unique() %>%
    group_by(M, Stage) %>% 
    add_tally() %>% 
    group_by(M) %>% 
    mutate(perc = n / sum(n)) %>%
    select(M, Stage, perc) %>% 
    unique()

temp = dcast(temp, M~Stage, value.var = "perc")

temp$M <- paste0("M", temp$M)

rownames(temp) <- temp$M

temp = temp[, colnames(temp) != "M"]

Heatmap(
    temp, 
    cluster_rows = F, 
    cluster_columns = F, 
    name = "perc",
    cell_fun = function(j, i, x, y, width, height, fill) {
        if(!is.na(temp[i, j ]))
            grid.text(sprintf("%.2f", temp[i, j]), x, y, gp = gpar(fontsize = 10))
    }
)
```


### Test PCA

```{r}
pca <- prcomp(t(lfp), center = F, scale. = F)
```


```{R fig.height=12, fig.width=16}
library(ggfortify)

colours = data.frame(id=colnames(lfp))

plist = list()
for(i in 1:(min(ncol(pca$x), 10) - 1)) {
    p = autoplot(pca, data=colours, colour = "id", x=i, y=i + 1, label=TRUE, shape = FALSE) + theme(legend.position = "none")
    plist[[i]] <- p
}

cowplot::plot_grid(plotlist = plist, ncol = 4)
```

---
### APII


```{r}
obj <- readRDS("/mnt/raid62/Lung_cancer_10x/02_figures_each_cell/Alveolar_II_ADC/Alveolar_II.rds")
```

This is how to export lfp value
```{R}
load("/mnt/raid62/Lung_cancer_10x/MetaCell/By_cells/Alveolar_II_ADC/mat.Alveolar_II_ADC.Rda")
scmat = object


load("/mnt/raid62/Lung_cancer_10x/MetaCell/By_cells/Alveolar_II_ADC/mc.Alveolar_II_ADC_mc_f.Rda")
mc = object

load("/mnt/raid62/Lung_cancer_10x/MetaCell/By_cells/Alveolar_II_ADC/gstat.Alveolar_II_ADC.Rda")
gstat = object

out_df = rbind(tapply(colSums(scmat@mat[, names(mc@mc)]), mc@mc, mean), table(mc@mc))
out_df = cbind(rep("", nrow(out_df)), out_df)


fp_max = apply(mc@mc_fp, 1, max)
fp_tot = gstat[intersect(rownames(mc@mc_fp), rownames(gstat)), "tot"]

# genes to export
f = fp_max > 0 & fp_tot > 0

# actual clust_fp
# out_df = rbind(out_df, cbind(rep("", sum(f)), round(log2(mc@mc_fp[f,]), 2)))
# out_df <- out_df[, 2:ncol(out_df)]

# rownames(out_df)[1:2] = c('mean_umis', 'n_cells')

lfp = round(log2(mc@mc_fp[f,]), 2)
```


```{r}
markers <- read.xlsx("/mnt/raid62/Lung_cancer_10x/02_figures_each_cell/Alveolar_II_ADC/annotation_results_by_cluster.xlsx", rowNames = T)

markers <- as.data.frame(markers %>% filter(p_val_adj < 0.05) %>% group_by(ident) %>% top_n(10, wt = avg_logFC))
```

```{R fig.height=12, fig.width=8}
pheatmap::pheatmap(lfp[markers$gene[markers$gene %in% rownames(lfp)], ], cluster_rows = F)
```

```{r fig.height=12, fig.width=8}
DoHeatmap(obj, genes.use = intersect(markers$gene, rownames(lfp)), group.by = "res.0.6", slim.col.label = T)
```

---
Test Stage module

```{r}
markers <- read.xlsx("/mnt/raid62/Lung_cancer_10x/02_figures_each_cell/Alveolar_II_ADC/annotation_results_by_stage.xlsx", rowNames = T)

markers <- as.data.frame(markers %>% filter(p_val_adj < 0.05) %>% group_by(ident) %>% top_n(10, wt = avg_logFC))
```

```{R fig.height=12, fig.width=8}
pheatmap::pheatmap(lfp[intersect(markers$gene, rownames(lfp)), ], cluster_rows = F)
```

```{r}
DoHeatmap(obj, genes.use = intersect(markers$gene, rownames(lfp)), group.by = "Stage", slim.col.label = T)
```

### lets check the percentage of different stage cells

```{r}
clt = as.data.frame(mc@mc)
colnames(clt) = "MetaCell"

clt$Stage = obj@meta.data[rownames(clt), "Stage"]
clt$clt = obj@meta.data[rownames(clt), "res.0.6"]
```

```{r}
temp = clt %>% 
    select(MetaCell, clt) %>% 
    unique() %>%
    group_by(MetaCell, clt) %>% 
    add_tally() %>% 
    group_by(MetaCell) %>% 
    mutate(perc = n / sum(n)) %>%
    select(MetaCell, clt, perc) %>% 
    unique()

temp = dcast(temp, MetaCell~clt, value.var = "perc")

temp$MetaCell <- paste0("MetaCell", temp$MetaCell)

rownames(temp) <- temp$MetaCell

temp = temp[, colnames(temp) != "MetaCell"]
# temp[is.na(temp)] = 0

pheatmap::pheatmap(temp, number_format = "%.2f", display_numbers = T, cluster_rows = F, cluster_cols = F)
```



```{r}
temp = clt %>% 
    select(MetaCell, Stage) %>% 
    unique() %>%
    group_by(MetaCell, Stage) %>% 
    add_tally() %>% 
    group_by(MetaCell) %>% 
    mutate(perc = n / sum(n)) %>%
    select(MetaCell, Stage, perc) %>% 
    unique()

temp = dcast(temp, MetaCell~Stage, value.var = "perc")

temp$MetaCell <- paste0("MetaCell", temp$MetaCell)

rownames(temp) <- temp$MetaCell

temp = temp[, colnames(temp) != "MetaCell"]
# temp[is.na(temp)] = 0

pheatmap::pheatmap(temp, number_format = "%.2f", display_numbers = T, cluster_rows = F, cluster_cols = F)
```


### Test PCA

```{r}
pca <- prcomp(t(lfp), center = F, scale. = F)
```


```{R fig.height=12, fig.width=16}
library(ggfortify)

colours = data.frame(id=colnames(lfp))

plist = list()
for(i in 1:(min(ncol(pca$x), 10) - 1)) {
    p = autoplot(pca, data=colours, colour = "id", x=i, y=i + 1, label=TRUE, shape = FALSE) + theme(legend.position = "none")
    plist[[i]] <- p
}

cowplot::plot_grid(plotlist = plist, ncol = 4)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
