---
title: "Compare_with_NM"
author: "Zhang Yiming"
date: "7/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{R}
library(openxlsx)
library(ggplot2)
library(Seurat)
library(cowplot)
library(stringr)
library(dplyr)
library(reshape2)
library(tidyr)


full.path = function(path) {
    return(paste("/mnt/raid62/Lung_cancer_10x/MetaCell", path, sep = "/"))
}


# R is mess up
read_lfp <- function(path) {
    data = read.csv(path, header = T, row.names = 1)
    
    mat = matrix(NA, nrow = nrow(data), ncol = ncol(data))
    
    for(i in 1:length(data)) {
        mat[, i] = data[[i]]
    }
    
    rownames(mat) <- rownames(data)
    colnames(mat) <- names(data)
    as.matrix(mat)
}


# function to make grid Dotplot
DotPlotGrid <- function(object, markers, group.by = "res.0.6") {
    mat = object@scale.data[intersect(markers$Markers, rownames(object@scale.data)), ]
    mat = as.data.frame(t(mat))
    

    mat = melt(as.matrix(mat))
    mat$group = object@meta.data[mat$Var1, group.by]
    mat = merge(mat, markers, by.x = "Var2", by.y = "Markers")
    
    mat <- mat %>% 
        group_by(Var2, Cells, group) %>% 
        mutate(m = mean(value)) %>% 
        mutate(p = sum(value > 0) / n()) %>%
        select(Var2, value, group, Cells, m, p) %>% 
        unique()
    
    ggplot(data = mat, aes(x=group, y=Var2, color = m, size = p)) +
        geom_point() +
        facet_grid(Cells~., scales = "free", space = "free")
    
}
```


## Read data

```{r cars}
random_sel <- read_lfp(full.path("lfp/huaxi_selected_mc_f.log2_mc_fp.txt"))
colnames(random_sel) <- paste0("HX", 1:ncol(random_sel))

nm_sel <- read_lfp(full.path("lfp/NM_selected_mc_f.log2_mc_fp.txt"))
colnames(nm_sel) <- paste0("DL", 1:ncol(nm_sel))
```

```{r}
mat <- cbind(random_sel[intersect(rownames(random_sel), rownames(nm_sel)), ], nm_sel[intersect(rownames(random_sel), rownames(nm_sel)), ])
```

## Perform Seurat
```{r}
obj <- CreateSeuratObject(
    as.matrix(mat), 
    meta.data = data.frame(
        source = c(
            rep("HX", ncol(random_sel)), 
            rep("DL", ncol(nm_sel))
        )
    )
)

obj@meta.data$source <- sapply(colnames(obj@raw.data), function(x) {
    str_replace(x, "\\d+", "")
})
```


## Skip Scale, just run PCA and tSNE
```{r}
obj@scale.data = obj@raw.data

obj <- FindVariableGenes(object = obj, mean.function = ExpMean, dispersion.function = LogVMR, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)

obj <- RunPCA(object = obj, pc.genes = obj@var.genes, do.print = FALSE, pcs.compute = 100)
```

select PCs
```{r fig.height=4, fig.width=12}
PCElbowPlot(obj, num.pc=100)  +
    scale_x_continuous(breaks=1:100) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

Run tSNE
```{R}
n.pcs = 10

obj <- RunTSNE(object = obj, dims.use = 1:n.pcs, do.fast = TRUE, reduction.use = "pca", reduction.name = "tsne")
obj <- FindClusters(object = obj, reduction.type = "pca", dims.use = 1:n.pcs, resolution = 0.6, print.output = 0, save.SNN = FALSE, force.recalc = TRUE)
```


Check the clusters
```{r fig.height=6, fig.width=12}
p1 <- DimPlot(
    obj, 
    reduction.use = "tsne", 
    group.by = "res.0.6", 
    no.legend = TRUE, 
    do.label = TRUE, 
    label.size = 8, 
    do.return = TRUE
)

p2 <- DimPlot(
    obj, 
    reduction.use = "tsne", 
    group.by = "source", 
    no.legend = FALSE, 
    do.label = FALSE, 
    label.size = 8, 
    do.return = TRUE
)

plot_grid(p1, p2, nrow = 1, rel_widths = c(1, 1.2))
```

### make dot plot by known markers
```{r}
markers <- read.xlsx("/mnt/raid62/Lung_cancer_10x/00_data_ingest/03_annotation_csv/20190701_gene_markers.xlsx", sheet = 1)

markers <- markers[markers$Markers %in% rownames(obj@raw.data), ]
```

```{R fig.height=36, fig.width=12}
PercentAbove <- function(x, threshold){
  return(length(x = x[x > threshold]) / length(x = x))
}


ModifiedDotPlot <- function(
  object,
  group.by,
  markers,
  cols.use = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  scale.by = 'radius',
  scale.min = NA,
  scale.max = NA,
  x.axis.rotate = FALSE
) {
  scale.func <- switch(
    EXPR = scale.by,
    'size' = scale_size,
    'radius' = scale_radius,
    stop("'scale.by' must be either 'size' or 'radius'")
  )
  if (!missing(x = group.by)) {
    object <- SetAllIdent(object = object, id = group.by)
  }
  
  genes.plot <- intersect(row.names(object@raw.data), markers$Markers)

  data.to.plot <- data.frame(FetchData(object = object, vars.all = genes.plot))
  colnames(x = data.to.plot) <- genes.plot
  data.to.plot$cell <- rownames(x = data.to.plot)
  data.to.plot$id <- object@ident
  data.to.plot %>% gather(
    key = genes.plot,
    value = expression,
    -c(cell, id)
  ) -> data.to.plot
  data.to.plot %>%
    group_by(id, genes.plot) %>%
    summarize(
      avg.exp = mean(expm1(x = expression)),
      pct.exp = PercentAbove(x = expression, threshold = 0)
    ) -> data.to.plot
  data.to.plot %>%
    ungroup() %>%
    group_by(genes.plot) %>%
    mutate(avg.exp.scale = scale(x = avg.exp)) %>%
    mutate(avg.exp.scale = MinMax(
      data = avg.exp.scale,
      max = col.max,
      min = col.min
    )) ->  data.to.plot
  data.to.plot$genes.plot <- factor(
    x = data.to.plot$genes.plot,
    levels = rev(x = genes.plot)
  )
  # data.to.plot$genes.plot <- factor(
  #   x = data.to.plot$genes.plot,
  #   levels = rev(x = sub(pattern = "-", replacement = ".", x = genes.plot))
  # )
  data.to.plot$pct.exp[data.to.plot$pct.exp < dot.min] <- NA
  data.to.plot$pct.exp <- data.to.plot$pct.exp * 100
  data.to.plot <- merge(data.to.plot, markers, by.x = "genes.plot", by.y = "Markers")
  
  p <- ggplot(data = data.to.plot, aes(x = id, y = genes.plot, size = pct.exp, color = avg.exp.scale)) + 
    geom_point() + 
    # guides(
    #     color=guide_legend(
    #         ncol = 2,
    #         title.position = "top"
    #     ),
    #     size=guide_legend(
    #         ncol = 1
    #     ),
    #     alpha=guide_legend(
    #         ncol = 1
    #     )
    # ) +
    scale.func(range = c(0, dot.scale), limits = c(scale.min, scale.max)) +
    facet_grid(Cells ~ ., scale = "free", space = "free") +
      scale_color_gradient(low = "lightgrey", high = "blue")
  
  if (x.axis.rotate) {
    p = p + theme(
        legend.position = "none",
        axis.title.x = element_blank(), 
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
    )
  } else {
    p = p + theme(
        legend.position = "none",
        axis.title.x = element_blank(), 
        axis.title.y = element_blank(),
        axis.text.x = element_text(hjust = 1, vjust = 0.5)
        # axis.title.y = element_text(angle = 90)
    )
  }
  
  
  return(p)
}


ModifiedDotPlot(obj, markers = markers, group.by = "res.0.6")
```

```{r fig.height=36, fig.width=12}
DotPlot(
    obj, genes.plot = unique(markers$Markers), plot.legend = TRUE, x.lab.rot = T,
    do.return = T
) + coord_flip()
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
