---
title: "Test_scBio_to_split_metacell"
author: "Zhang Yiming"
date: "7/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(scBio)
library(ggplot2)
library(Rtsne)
library(FactoMineR)
```



```{r cars}
load("/mnt/raid62/Lung_cancer_10x/MetaCell/immu_all/mat.immu_all.Rda")
mat = object
mat = as.matrix(mat@mat)

metacell = read.csv("/mnt/raid62/Lung_cancer_10x/MetaCell/lfp/immu_all_mc_f.log2_mc_fp.txt", row.names = 1)

meta <- read.csv("/mnt/raid62/Lung_cancer_10x/00_data_ingest/03_annotation_csv/20190506_meta.csv", row.names = 1)

metacell <- readRDS("/mnt/raid62")
```


```{r}
pca = read.csv("/mnt/raid62/Lung_cancer_10x/MetaCell/immu_all/mat.immu_all.pca.csv", row.names = 1)
colnames(pca) <- paste0("PC", 1:ncol(pca))
```


## do tsne
```{r fig.height=6, fig.width=20}
temp = as.data.frame(apply(pca, 2, sd))
colnames(temp) <- c("SD")
temp$PC = factor(rownames(temp), levels = rownames(temp))

ggplot(temp[1:100,], aes(x = PC, y = SD)) + geom_point() + theme(axis.text.x = element_text(angle = 90))
```


```{r}
tsne_coord = Rtsne(pca[, 1:9])
tsne_coord = tsne_coord$Y
rownames(tsne_coord) = colnames(lfp)
```


```{r}
common_genes = intersect(rownames(mat@mat), rownames(metacell))

res = CPM(
    SCData = mat@mat[common_genes, ], 
    SCLabels = meta[colnames(mat@mat), "cell_name"], 
    BulkData = metacell[common_genes, ],
    cellSpace = as.matrix(tsne_coord), 
    quantifyTypes = T, 
    typeTransformation = T, 
    no_cores = 6
)
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
