---
title: "tSNE_on_selected_cells"
author: "Zhang Yiming"
date: "2019/6/28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(Rtsne)
library(stringr)
```


### SCC
```{R}
expr = read.csv("/mnt/raid62/Lung_cancer_10x/URSM/SCC/single_cell_expr.csv", header = F)

cells = read.csv("/mnt/raid62/Lung_cancer_10x/URSM/SCC/single_cell_expr_cells.txt", header = F)

genes = read.csv("/mnt/raid62/Lung_cancer_10x/URSM/SCC/single_cell_expr_genes.txt", header = F)

meta = read.csv("/mnt/raid62/Lung_cancer_10x/URSM/SCC/meta.csv", row.names = 1)
```


```{R}
rownames(expr) <- cells$V1
colnames(expr) <- genes$V1
```

```{R}
set.seed(1)

sel_expr = expr[sample(1:nrow(expr), 1500), ]

pca = prcomp(sel_expr)
```

select pca
```{R fig.height=6, fig.width=12}
temp = as.data.frame(apply(pca$x, 2, sd))
temp$x = rownames(temp)
colnames(temp) <- c("y", "x")

temp$x = factor(temp$x, levels = temp$x)

ggplot(data = temp[1:100,], aes(x=x, y=y)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
    labs(x = "", y = "")
```


```{r fig.height=6, fig.width=8}
tsne = Rtsne(X=pca$x[, 1:5], dims = 2)

tsne_coord = as.data.frame(tsne$Y)
tsne_coord$x = rownames(pca$x)

colnames(tsne_coord) <- c("tSNE_1", "tSNE_2", "cell_id")


ggplot(
    tsne_coord, 
    aes(x=tSNE_1, y=tSNE_2)
) + 
    geom_point() +
    theme(legend.position = "none")
```
### Saving
```{R}
saveRDS(sel_expr, "/mnt/raid62/Lung_cancer_10x/URSM/SCC_random/expr.rds")

saveRDS(tsne_coord, "/mnt/raid62/Lung_cancer_10x/URSM/SCC_random/tsne_coord.rds")


write.table(sel_expr, "/mnt/raid62/Lung_cancer_10x/URSM/SCC_random/single_cell_expr.csv", col.names = F, row.names = F, quote = F, sep = ",")

write.table(colnames(sel_expr), "/mnt/raid62/Lung_cancer_10x/URSM/SCC_random/single_cell_expr_genes.txt", row.names = F, col.names = F, quote = F)


unique_cells <- data.frame(
    cell_name = sort(unique(meta$cell_name)),
    cell_types = 1:length(unique(meta$cell_name))
)
unique_cells$cell_types = unique_cells$cell_types - 1
rownames(unique_cells) <- unique_cells$cell_name


cell_types = meta[rownames(sel_expr), "cell_name"]
cell_types = unique_cells[cell_types, "cell_types"]

write.table(cell_types, "/mnt/raid62/Lung_cancer_10x/URSM/SCC_random/single_cell_expr_cells_type.csv", row.names = F, col.names = F, quote = F)
```

### ADC
```{R}
expr = read.csv("/mnt/raid62/Lung_cancer_10x/URSM/ADC/single_cell_expr.csv", header = F)

cells = read.csv("/mnt/raid62/Lung_cancer_10x/URSM/ADC/single_cell_expr_cells.txt", header = F)

genes = read.csv("/mnt/raid62/Lung_cancer_10x/URSM/ADC/single_cell_expr_genes.txt", header = F)

meta = read.csv("/mnt/raid62/Lung_cancer_10x/URSM/ADC/meta.csv", row.names = 1)
```


```{R}
rownames(expr) <- cells$V1
colnames(expr) <- genes$V1
```

```{R}
set.seed(1)

sel_expr = expr[sample(1:nrow(expr), 1500), ]

pca = prcomp(sel_expr)
```

select pca
```{R fig.height=6, fig.width=12}
temp = as.data.frame(apply(pca$x, 2, sd))
temp$x = rownames(temp)
colnames(temp) <- c("y", "x")

temp$x = factor(temp$x, levels = temp$x)

ggplot(data = temp[1:100,], aes(x=x, y=y)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
    labs(x = "", y = "")
```


```{r fig.height=6, fig.width=8}
tsne = Rtsne(X=pca$x[, 1:10], dims = 2)

tsne_coord = as.data.frame(tsne$Y)
tsne_coord$x = rownames(pca$x)

colnames(tsne_coord) <- c("tSNE_1", "tSNE_2", "cell_id")


ggplot(
    tsne_coord, 
    aes(x=tSNE_1, y=tSNE_2)
) + 
    geom_point() +
    theme(legend.position = "none")
```
### Saving
```{R}
saveRDS(sel_expr, "/mnt/raid62/Lung_cancer_10x/URSM/ADC_random/expr.rds")

saveRDS(tsne_coord, "/mnt/raid62/Lung_cancer_10x/URSM/ADC_random/tsne_coord.rds")


write.table(sel_expr, "/mnt/raid62/Lung_cancer_10x/URSM/ADC_random/single_cell_expr.csv", col.names = F, row.names = F, quote = F, sep = ",")

write.table(colnames(sel_expr), "/mnt/raid62/Lung_cancer_10x/URSM/ADC_random/single_cell_expr_genes.txt", row.names = F, col.names = F, quote = F)


unique_cells <- data.frame(
    cell_name = sort(unique(meta$cell_name)),
    cell_types = 1:length(unique(meta$cell_name))
)
unique_cells$cell_types = unique_cells$cell_types - 1
rownames(unique_cells) <- unique_cells$cell_name


cell_types = meta[rownames(sel_expr), "cell_name"]
cell_types = unique_cells[cell_types, "cell_types"]

write.table(cell_types, "/mnt/raid62/Lung_cancer_10x/URSM/ADC_random/single_cell_expr_cells_type.csv", row.names = F, col.names = F, quote = F)
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
