---
title: "Tmod_plots"
author: "Zhang Yiming"
date: "2019/6/10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(openxlsx)
library(tagcloud)
library(openxlsx)

```

```{r cars}

read_data <- function(path, sheet=1, p.val = 0.05) {
    data = read.xlsx(path, sheet = sheet)
    data = data[data$P.Value < 0.05, ]
    data
}

msd = read_data("tmod.xlsx", sheet = 1)
logfc = read_data("tmod.xlsx", sheet = 2)
p_adj = read_data("tmod.xlsx", sheet = 3)
pcs = read_data("tmod.xlsx", sheet = 4)
```


### tagclouds based on MSD results
```{r fig.height=8, fig.width=8}
make_tagcloud_plots <- function(data) {
    for (i in unique(data$module)) {
        temp = data[data$module == i, ]
        
        # par(
        #     mfrow=c(2, 1),
        #     mar = c(0, 0, 0, 0),
        #     cex = 1
        # )
        
        # layout(matrix(c(1,2)), heights=c(1,2))
        # plot.new()
        # text(x=0.5, y=0.5, i)
        
        if (nrow(temp) <=1 ) {
            print(i)
            print(temp$Title)
            next
        }
        
        w <- -log10(temp$P.Value)
        c <- smoothPalette(temp$AUC, min=0.5)
        tags <- strmultline(temp$Title)
        tagcloud(tags, weights=w, col=c)
        mtext(i, side=3, outer=TRUE, line=-1) 
    }
}

make_tagcloud_plots(msd)
```

### tagclouds based on logFC results
```{R}
make_tagcloud_plots(logfc)
```


### tagclouds based on p_adj_val results
```{R}
make_tagcloud_plots(p_adj)
```


### tagclouds based on pcs results
```{R}
make_tagcloud_plots(pcs)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
